export const EnumApiConstants = {
  SalesforceEdPlus: "SalesforceEdPlus",
  UgAppPath: "ug-app",
};

export const EnumUndergradAppScreenLabels = {
  PageUndergradMyInformation: "My information",
  PageUndergradMyProgram: "My program",
  PageUndergradMySchools: "My schools",
  PageUndergradMyHighSchoolGrades: "My high school grades",
  PageUndergradArizonaResidency: "Arizona residency",
  PageUndergradReview: "Review",
  PageUndergradAppDashboard: "Post submission dashboard",
};

export const EnumPageNames = {
  PageHome: "home",
  PageDashboard: "dashboard",
  PageOAuth2CallBack: "oauth2-callback",
  PageImpersonationCallBack: "impersonation-callback",
  PagePaymentNelnetCallback: "payment-nelnet-callback",
  PageUserCreateAccount: "user-create-account",
  PageUserVerifyEmail: "user-verify-email",
  PageUserLogin: "user-login",
  PageUserResetPassword: "user-reset-password",
  PageUserNewPassword: "user-new-password",
  PageUserNewPasswordConfirm: "user-new-password-confirm",
  PageProfile: "profile",
  PageProfileResetPassword: "profile-reset-password",
  PageProfileNewPassword: "profile-new-password",
  PageProfileNewPasswordConfirm: "profile-new-password-confirm",
  PageProfileEditName: "profile-edit-name",
  PageProfileEditPreferredFirstName: "profile-edit-preferred-first-name",
  PageProfileEditBirthday: "profile-edit-birthday",
  PageProfileEditPronoun: "profile-edit-pronoun",
  PageProfileEditGender: "profile-edit-gender",
  PageProfileEditPhoneNumber: "profile-edit-phone-number",
  PageUndergradHome: "ug-app-home",
  PageUndergradMyInformation: "ug-app-my-information",
  PageUndergradMyProgram: "ug-app-my-program",
  PageUndergradMySchools: "ug-app-my-schools",
  PageUndergradMyHighSchoolGrades: "ug-app-my-high-school-grades",
  PageUndergradArizonaResidency: "ug-app-arizona-residency",
  PageUndergradReview: "ug-app-review",
  PageUndergradPreview: "ug-app-preview",
  PageUndergradDashboard: "ug-app-dashboard",
  PageError: "error",
  PageMaintenance: "maintenance",
  PageNotFound: "not-found",
};
