name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Yarn develop
        run: yarn dev

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn test:e2e:ci:api-testing
          browser: chrome

