name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome

      - name: Run Cypress Shell Script
        run: sh ./runcypress.sh

