name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      # Start the Docker daemon in the GitHub Actions runner
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Build Docker Image
        run: |
          docker build -t uga-docker .

      - name: Run Cypress Tests in Docker
        run: |
          docker run -v ${{ github.workspace }}:/app -w /app uga-docker ./runcypress.sh
